development:
  adapter: postgresql
  encoding: unicode
  database: plastiq_development
  pool: 5
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: plastiq_test
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: plastiq_production
  pool: 5